### ISSUE TITLE
Can't portctl certain, specific ports

### ISSUE THREAD

**Issue by NMCPaul** [netdisco/netdisco#1145]
## Expected Behavior
I would expect to be able to portcontrol any and all ports if I haven't set restrictions in the `deployment.yml` file, which I haven't.

## Current Behavior
Certain ports don't allow me to run any sort of portcontrol operations on them.  The only commonality is when a Native VLAN has a name/link in it instead of just a number, like so:

![image](https://github.com/netdisco/netdisco/assets/1429743/45329139-5675-4c84-bcff-f5496a09fe45)

Everything blurred is a link, and none of them can be changed (bounced, renamed,etc).  The ones above it (Native VLAN = 1) are changeable.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
I don't have steps to reproduce as I don' t know why it's happening in the first place,

## Context
Trying to update descriptions and be able to bounce a port so I can reboot remote WAPs more easily.

## Your Environment
* Netdisco version used: 2.71.1
* SNMP::Info version used: 3.95

## Config info (deployment.yml)
There's not much extra in there, but I did make sure to set `portctl_nowaps: false` and limit some discovery via `discover_no` ACLs.

## Device information
I've noticed this on ANY port that has a Native VLAN that shows as a link, not just the WAPs that are showing in this screenshot.

**Comment by NMCPaul** [comment]
Here's another screenshot:

![image](https://github.com/netdisco/netdisco/assets/1429743/580935df-b8b0-467e-a506-64685306ae2c)

The top one - without the Native VLAN as a link and with the phone icon - can be altered.  The bottom one - the one WITH a Native VLAN link and without the phone icon even though it's clearly a phone - is not able to be edited.  And "198.108.197.0" is VLAN 6, so why it's rendering those 2 things differently isn't clear either.

**Comment by ollyg** [comment]
Hi @NMCPaul 

We did recently discover a few bugs in the port control ACL logic including how things are displayed in the web. I've just released 2.072000 and it would be great if you could test and let me know how it is now.

However, some of the ports you show, particularly in the first screenshot) are legitimate "uplinks" and Netdisco will not allow port control on them unless "portctl_uplinks" is true. Please see the updated configuration documentation for details of the several "portctl_*" settings.

regards
oliver.

**Comment by NMCPaul** [comment]
I upgraded to v2.71.1 via the cURL command in the docs.  Unfortunately, it didn't resolve the issue, nor did setting `portctl_uplinks: true`.  Can't bounce the port nor change the VLAN.   I took a new screenshot that might illustrate it a little:

![image](https://github.com/netdisco/netdisco/assets/1429743/eddf30ee-5a71-49b5-ae20-a40300ea4268)

Gi1/0/25 and Gi1/0/27 are identical.  They are both workstations that are connected via PoE deskphones, yet I can't manipulate the Gi1/0/27 port at all.  Since they are workstations, I wouldn't consider either of them uplinks, but I don't know the ins and outs of the heuristics that determine what an uplink actually is.

Thanks.

**Comment by ollyg** [comment]
Hi @NMCPaul I asked if you could upgrade to 2.072000 but you mentioned v2.71.1.
Please can you confirm which version is running? Ideally upgrade to 2.072000 and run full discover again.
Many thanks

**Comment by NMCPaul** [comment]
Apologies, but here's how I upgraded:

![image](https://github.com/netdisco/netdisco/assets/1429743/9d34a7de-4a10-4ef6-a366-01a9f5a1c679)

And here's what I see on the main screen:

![image](https://github.com/netdisco/netdisco/assets/1429743/3d5704d6-9d40-41c1-8f2b-016f75f5f064)

Uncertain how to upgrade in a different way to a specific version, but I'm game if you could point me in the right direction.

**Comment by ollyg** [comment]
Hi @NMCPaul 
OK I'm not sure why it's not picking up the latest release!
You can try the following more direct approach instead:

```
~netdisco/bin/localenv cpanm https://cpan.metacpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.072000.tar.gz
```

thanks
Oliver.

**Comment by ollyg** [comment]
oh, did you run netdisco-deploy afterwards and accept all the options "yes" ?

**Comment by ollyg** [comment]
Hi Paul

Yes the steps as listed here:
https://metacpan.org/pod/App::Netdisco#Upgrading-from-2.x

Regards
Oliver.

**Comment by NMCPaul** [comment]
Got it.  Ran everything and while it shows this in the web...

![image](https://github.com/netdisco/netdisco/assets/1429743/bb9b0c6f-da7e-4f17-8e14-05e5e03338d5)

the CLI shows `App::Netdisco is up to date. (2.072000)` so I'm up to date.

I re-discovered the device I've been testing on, and no change.  It's flagging a LOT of things as "possible uplink":

![image](https://github.com/netdisco/netdisco/assets/1429743/d18fbb4a-3b51-4d73-a501-ca173eba8d53)

Is this because there's 2 VLANs?  Because one is the switchport VLAN and the other is the voice VLAN.

**Comment by ollyg** [comment]
Progress, thanks this helps. I will probably make a point release later
this evening then we can test again.

**Comment by NMCPaul** [comment]
Well you were right - it fixed a LOT of stuff.  Thanks!

For future reference, is there a way to run some sort of debug, tell-me-what-heuristics-you-used-that-makes-you-think-this-is-an-uplink-port loglevel?  I'd be game to run it and provide it to you if you'd find it useful if I run into any othersimilar issues.

**Comment by ollyg** [comment]
Hi @NMCPaul many thanks for the quick feedback! I'm so pleased things look better now.
For the debug, we do have the -D flag on netdisco-do which emits additional logging. For example if you run:
```
~netdisco/bin/netdisco-do discover -d x.x.x.x -D
````
There might be missing log lines, but it tends to be quite verbose for ports.
I'll close this ticket for now, feel free to contact again or ask on IRC/email if you have questions.
