### ISSUE TITLE
Neighbors view shows devices stacked on top of each other....but only for certain devices

### ISSUE THREAD

**Issue by lwhitworth** [netdisco/netdisco#314]
When looking at Neighbors tab for _some_ devices they display stacked on top of each other:

![not_working](https://user-images.githubusercontent.com/4669414/27120059-118f35ca-50da-11e7-969c-2b841c39c233.JPG)

Works as expected for other devices.  Seems to be the devices on the end of a chain that render this way.  So in the below image the issue manifests for cchppc9-064-04.ccc and cchppc9-063-09.ccc but not for any of the other nodes.

![working](https://user-images.githubusercontent.com/4669414/27120058-118ec158-50da-11e7-999f-4052096de557.JPG)

I have two Netdisco2 instances and this only manifests on one.  They're both on the same version of Netdisco2 (2.035006) but there is a Perl version difference that might be causing it.  Other key versions:

Working server:
**App::Netdisco:**	2.035006
**DB Schema:** v41
**Dancer:** 1.3134
**Bootstrap:** 2.3.1
**PostgreSQL:** PostgreSQL 8.4.22 on i686-redhat-linux-gnu, compiled by GCC gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54), 32-bit. DBI 1.63, DBD::Pg 2.19.3
**SNMP::Info:** 3.34
**Perl:** 5.018001

Not working server:
**App::Netdisco:** 2.035006
**DB Schema:** v41
**Dancer:** 1.3202
**Bootstrap:** 2.3.1
**PostgreSQL:** PostgreSQL 9.2.18 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-9), 64-bit. DBI 1.636, DBD::Pg 2.19.3
**SNMP::Info:** 3.34
**Perl:** 5.016003

I'm trying to debug to see if I can find any more relevant info but not getting very far!  Let me know if there's any further info that I can supply that would help.

Cheers

**Comment by ollyg** [comment]
Hi @lwhitworth 

I have just released Netdisco 2.036009 to CPAN with some changes to how the netmap works. Please would you re-test and let me know if it makes a difference?

thanks
Oliver.

**Comment by lwhitworth** [comment]
I've just run through an upgrade and am still seeing the same issue.

When I look in the web interface though I still see:
App::Netdisco | 2.36.7

However, in the logs I am seeing [3323] 2017-08-01 13:27:06  warn App::Netdisco 2.036009 web

**Comment by lwhitworth** [comment]
Just tried a fresh install on a fresh VM, same issue still persists I'm afraid

**Comment by ollyg** [comment]
OK thanks for checking. Also the reason you see the old version in the web is because that data is from the stats DB which is only updated once a day.

**Comment by edo1** [comment]
I have the same issue. How can I help?

**Comment by ollyg** [comment]
Hi both - we have a new network map in the latest release of Netdisco. If you upgrade I think you will find it an improvement 😊. Thanks for the bug report which inspired me to work on the issue!
