### ISSUE TITLE
Netdisco 2 Search Node Date Range Problem

### ISSUE THREAD

**Issue by mkesoulis** [netdisco/netdisco#521]
Hello there,
I would like to report that when I try to Search a Node with a pre-configured Date Range (today, yesterday, etc...) or custom Date Range, Netdisco does not give any results with the message "No matching records".
I believe that the query should return all the Dates this Node was Seen in the specific Date Range.
I have attached two screenshots were a node is shown (2019-03-01) with no Date Range selected, but when I select Today (2019-03-01 to 2019-03-01) from Date Range there is no matching record. This is the same behavior for all the pre-configured selections as also for Custom Date Range.

Is this a bug of Netdisco?

Thanks in advance,

Marios

Software 	Version
App::Netdisco 	2.40.3
SNMP::Info 	3.64
DB Schema 	53
PostgreSQL 	9.5.14
Perl 	5.22.1

![no date range](https://user-images.githubusercontent.com/47447363/53636258-3827c680-3c28-11e9-8e2b-29d015268318.JPG)

![date range](https://user-images.githubusercontent.com/47447363/53636257-378f3000-3c28-11e9-8449-9369b6641101.JPG)

**Comment by inphobia** [comment]
can verify, am seeing the same issue. will need to have a closer look at the data parsing & the sql that get's generated. a quick check with DBIC_TRACE did not show anything obvious going wrong.

**Comment by ollyg** [comment]
Hi @mkesoulis thanks for the bug report! The fix will be in the next release:
[master 7a8bcb09] #521 Search Node Date Range not working

**Comment by mkesoulis** [comment]
Hello there,
sorry to say that, but the bug is not solved.
I have updated Netdisco to version 2.40.6 but it has the same behavior.
When you Search a Node with Date Range, Netdisco does not give any results with the message "No matching records".
Could you please open the again the issue and give it another look?
Thanks for the effort,
Marios


Software Version
App::Netdisco 	2.40.6
SNMP::Info 	3.65
DB Schema 	54
PostgreSQL 	9.5.14
Perl 	5.22.1

**Comment by ollyg** [comment]
Hi @mkesoulis unfortunately I cannot reproduce the issue. As you can see in the image below, on my system I have a node which has similar active dates to yours, and I enter the same sidebar parameters, and it is found (after the bug fix). Please would you double check you have restarted the netdisco-web instance and refreshed your browser fully?

![image](https://user-images.githubusercontent.com/29653/53799325-08cbcf00-3f32-11e9-8d4d-51c1b126021c.png)

**Comment by mkesoulis** [comment]
Hello Oliver,
I think I misunderstood something.
I thought that when I use a Date Range Netdisco will bring all the Dates that this node has been Seen and not only the Last Seen.
For example, if a device is Seen 2019-03-01, 03-02, 03-03... 03-05 when I use Date Range from 2019-03-01 to 2019-03-05 is showing only the Last Seen (2019-03-05) but I expected Netdisco to fetch all the dates that this device was seen in this Date Range.
If this is not a function of Netdisco then it is my mistake, although it would be a nice feature.
Am I mistake here?

**Comment by ollyg** [comment]
Ah OK, thanks for the clarification.

If the node has moved around, you can tick the "archived data" box in the
sidebar to get the results on other device ports. If the node has stayed in
the same place, you just get the one row (I think).

Hope that helps,

**Comment by ollyg** [comment]
(but you can see the first seen and last seen dates in the same row, too)

**Comment by mkesoulis** [comment]
> If the node has moved around, you can tick the "archived data" box in the sidebar to get the results on other device ports. If the node has stayed in the same place, you just get the one row (I think).

I am covered from the above answer. Thanks a lot again Oliver.

**Comment by mkesoulis** [comment]
Oliver,
sorry to bother again, but I believe that I discovered another problem.
If you Search a Node with MAC Address and Date Range, the search is failing with the message " Search failed! Please contact your site administrator."
Is this a bug?

**Comment by ollyg** [comment]
Hi @mkesoulis thanks for the report (again) - I have fixed this, I hope, and released 2.040007 to CPAN.

**Comment by mkesoulis** [comment]
Hi Oliver,
the last issue I reported unfortunately is not solved.
I repeat the problem: When you Search a Node with **MAC Address** (not IP) and you use Date Range (today, yesterday etc...) the search is failing with the message "Search failed! Please contact your site administrator." If you don't use Date Range the results are fine.

**Comment by ollyg** [comment]
Hi - can you double check you're running 2.040007 now? I was able to
reproduce one failure of that sort which is fixed. Thank you,

**Comment by mkesoulis** [comment]
Oliver, I updated to 2.040007, restarted Netdisco web and backend, Update Statistics to verify that Netdisco is in the right version and finally restarted browser. The problem was there.
BUT, now tested again and is working fine.
Hmm, maybe it needed some time?
Again, I confirm that is working.
Thanks again and again.

**Comment by ollyg** [comment]
Okay, glad to hear and no worries 🙃
