### ISSUE TITLE
Network Map: Filter by VLAN doesn't work as expected

### ISSUE THREAD

**Issue by kkesper** [netdisco/netdisco#677]
## Expected Behavior

As stated in the User Guide the switches which are shown in the map should have at least one port in the VLAN specified in the filter. 

## Current Behavior

Instead all devices are shown where this VLAN is known.  Since we use Cisco VTP domains, this means that all the devices in the VTP domain are shown, regardless which VLAN in the domain is selected.

## Possible Solution

In a former version (i don't know the exact number, but before 2.42.10) the behaviour was correct.

## Steps to Reproduce (for bugs)

1. select Neighbors tab
2. enter a VLAN number in "carrying VLAN", which is known at some devices, which have no port carrying it.
3. select Redraw Map
4. These devices appear erroneously in the map.

## Context

These VLAN-maps are very useful in a large network with a complicated VLAN structure. Unfortunately the current behaviour makes this featuere unusuable

## Your Environment

* Netdisco version used: 2.44.4
* SNMP::Info version used: 3.70

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by ollyg** [comment]
Good call, thanks for the report @kkesper.

Note to self: Changing `vlans` to `port_vlans` on the following lines (twice) should do it:
https://github.com/netdisco/netdisco/blob/b211c7c7e20c812319f407f348eeb044297c54eb/lib/App/Netdisco/Web/Plugin/Device/Neighbors.pm#L211-L217

**Comment by kkesper** [comment]
I have tried your solution, and it worked in so far, as now the correct set of devices is shown. But now the links in between these devices are drawn at completely wrong positions in the graph. It seems, as if the connections are not "fixed" at the devices.

Interestingly enough, this only happens when the VLAN-filter is switched on.

**Comment by ollyg** [comment]
thanks @kkesper for testing it! that helped me find the issue which was on a DB JOIN returning too many rows. I've now implemented this fix and it will be in the next release.

[master d133eb97] #667 Network Map: Filter by VLAN doesnt work as expected

**Comment by ollyg** [comment]
I've accidentally committed this with the comment referring to #667

**Comment by kkesper** [comment]
I have installed version 2.44.5 now, and unfortunately this issue is not completely solved yet. The graph looks at first ok, but the positions of the devices don't move (as they do, when no VLAN-Filter is on) and it is also impossible to reposition any device, as the links between them stay fixed.

**Comment by ollyg** [comment]
Hi @kkesper please can you try clearing the cached netmap positions and check again?
````
netdisco-do psql -e 'delete from netmap_positions'
````
Thanks

**Comment by kkesper** [comment]
Sorry, but no change. As soon as the VLAN-filter is used, the graph "freezes". That means the links in between the devices are fixed to the background. The devices themselves can be moved but the links dont follow them and remain in the old position.

When i disable the VLAN-filter (selecting VLAN 0) everything is correct again.

**Comment by ollyg** [comment]
OK thanks, I'll take a look and see if I can reproduce it

**Comment by ollyg** [comment]
Hi @kkesper thanks, I found the bug and have released version 2.44.6 to CPAN.

[master ee86e62a] fix bug in vlan filtered netmap, duplicate nodes

**Comment by ollyg** [comment]
[master bb467972] smarter fix for vlan filter in netmap

**Comment by kkesper** [comment]
It runs perfectly now. Great work. Thanks a lot @ollyg!

These graphs are very valuable for us to keep track of our campus network's structure (~230 VLANs). So again, thanks a lot.

**Comment by ollyg** [comment]
My pleasure :-D
